
CREATE COLUMN TABLE T_PROPERTY_META
(
ID BIGINT CS_FIXED,
TENANT_ID NVARCHAR(32),
OBJECT_TYPE NVARCHAR(32),
"TYPE" NVARCHAR(32),
INTERNAL_NAME NVARCHAR(32),
DISPLAY_NAME NVARCHAR(32),
PARAM_INDEX INTEGER CS_INT
);

CREATE COLUMN TABLE T_VERSION_OBSERVER(
ID BIGINT CS_FIXED,
VERSION NVARCHAR(100),
OBSERVER_TYPE NVARCHAR(32),
TENANT_ID NVARCHAR(32)
);

CREATE COLUMN TABLE T_PROPERTY_COUNTING
(
ID BIGINT CS_FIXED,
OBJECT_TYPE NVARCHAR (32),
TENANT_ID NVARCHAR(32),
FIELD_NAME NVARCHAR (32),
COUNTING BIGINT null default 0
);

CREATE COLUMN TABLE TEST_ENTITY_A
(
ID BIGINT CS_FIXED,
NAME NVARCHAR(100),
TENANT_ID NVARCHAR(32)
);

CREATE COLUMN TABLE TEST_ENTITY_B
(
ID BIGINT CS_FIXED,
NAME NVARCHAR(100),
TENANT_ID NVARCHAR(32),
A_ID BIGINT
);

CREATE SEQUENCE T_PROPERTY_META_SEQ INCREMENT BY 1 START WITH 1 MINVALUE 1 NO CYCLE;
CREATE SEQUENCE VERSION_OBSERVER_SEQ INCREMENT BY 1 START WITH 1 MINVALUE 1 NO CYCLE;
CREATE SEQUENCE T_PROPERTY_COUNTING_SEQ INCREMENT BY 1 START WITH 1 MINVALUE 1 NO CYCLE;
CREATE SEQUENCE TEST_ENTITY_A_SEQ INCREMENT BY 1 START WITH 1 MINVALUE 1 NO CYCLE;
CREATE SEQUENCE TEST_ENTITY_B_SEQ INCREMENT BY 1 START WITH 1 MINVALUE 1 NO CYCLE;

INSERT INTO T_PROPERTY_META(ID, TENANT_ID, OBJECT_TYPE, TYPE, INTERNAL_NAME, DISPLAY_NAME, PARAM_INDEX) VALUES(T_PROPERTY_META_SEQ.nextval,'Tenant1','TestEntityB','NVARCHAR','UDF1' ,'userField1', 1);
INSERT INTO T_PROPERTY_META(ID, TENANT_ID, OBJECT_TYPE, TYPE, INTERNAL_NAME, DISPLAY_NAME, PARAM_INDEX) VALUES(T_PROPERTY_META_SEQ.nextval,'Tenant1','TestEntityB','NVARCHAR','UDF2' ,'userField2', 1);

ALTER TABLE TEST_ENTITY_B ADD (udf1 NVARCHAR(200));
ALTER TABLE TEST_ENTITY_B ADD (udf2 NVARCHAR(200));
